theme: minima
# Configurations
title: Amarnath A C
longtitle: Amarnath A C - Enthusiastic engineer working towards making this world a better place to live in!
email: acamarnath4@gmail.com

social:
  github: https://github.com/AmarnathAyyananChakkaravarthy
plugins:
  - jemoji
